# Generated by Django 5.2.8 on 2025-11-12 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name used in the draw_menu template tag.', max_length=100, unique=True)),
                ('title', models.CharField(blank=True, help_text='Optional human readable title shown in admin.', max_length=150)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('named_url', models.CharField(blank=True, help_text='Named URL pattern to use for this item (takes precedence over direct URL).', max_length=200)),
                ('url', models.CharField(blank=True, help_text='Direct URL for this item if named URL is not provided.', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the ordering of siblings inside the same parent.')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tree_menu.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.menuitem')),
            ],
            options={
                'verbose_name': 'Menu item',
                'verbose_name_plural': 'Menu items',
                'ordering': ('menu', 'parent__id', 'order', 'id'),
            },
        ),
    ]
